### ISSUE TITLE
Meta Title Resolution for nested pages

### ISSUE THREAD

**Issue by lucie1704** [intlify/bundle-tools#416]
### Clear and concise description of the problem

Can't find meta title with a nested page like "information/legal-mentions"
I get  :
`[intlify] Not found '/information/legal-mentions._meta.title' key in 'fr' locale messages.`

### Suggested solution

Either need to have a way to replicate the nested file architecture on the translation side like

locales/
├── en/
│   ├── home.json
│   ├── about.json
│   └── information/
│       ├── legal-mentions.json
│       └── privacy.json
└── fr/
    ├── home.json
    ├── about.json
    └── information/
        ├── legal-mentions.json
        └── privacy.json

so that it automatically exports information/legal-mentions keys as information.legal-mentions.m so that it can automatically target the _meta.title keys in the information/legal-mentions.json

Or else be able to modify the meta title path before resolution to be able to call your said file or even a single file with all meta titles 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
